### ISSUE TITLE
ERROR: createSsl's first argument must be a Buffer

### ISSUE THREAD

**Issue by skuchuk** [jSherz/node-grpc-mutual-auth-example#1]
Hi,
I am using the latest grpc v1.15.1
I get an error trying to use this example AS IS 
**grpc.credentials.createSsl expects a buffer not an object.**

If I buffer the first attribute in the passed object like this
{
    rootCerts: Buffer.from("content of crt file"),
    keyCertPairs: {
            privateKey: fs.readFileSync("path to key file"),
            certChain: fs.readFileSync("path to crt file")
    },
    checkClientCertificate: false
  }

I get this error: **addHttp2Port's second argument must be ServerCredentials**

Any idea what is the correct way to initialize the credentials object?

**Comment by czciou** [comment]
`server.bind('0.0.0.0:50051', grpc.ServerCredentials.createSsl(
          fs.readFileSync(path.join(process.cwd(), "server-certs", "Snazzy_Microservices.crt")),
          [
            {private_key: fs.readFileSync(path.join(process.cwd(), "server-certs", "login.services.widgets.inc.key")),
            cert_chain: fs.readFileSync(path.join(process.cwd(), "server-certs", "login.services.widgets.inc.crt"))}
          ]
          // [
          //   {private_key: fs.readFileSync(path.join(process.cwd(), "server-certs", "login.services.widgets.inc.key"))},
          //   {cert_chain: fs.readFileSync(path.join(process.cwd(), "server-certs", "login.services.widgets.inc.crt"))}
          // ]
        ));`

**Comment by czciou** [comment]
`
server.bind('localhost:50051', grpc.ServerCredentials.createSsl(
  fs.readFileSync(path.join(process.cwd(), "server-certs", "Snazzy_Microservices.crt")),
  [
    {private_key: fs.readFileSync(path.join(process.cwd(), "server-certs", "login.services.widgets.inc.key")),
    cert_chain: fs.readFileSync(path.join(process.cwd(), "server-certs", "login.services.widgets.inc.crt"))}
  ]
));
`

**Comment by jSherz** [comment]
Thanks for pointing this out and providing a working example. I've updated the code.
